/* Generated by Yosys 0.69+24 (git sha1 d0e71cfb7-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

module dac_output_stage(clk, reset, permit, valid, rgb_in, blank_in, hs_in, vs_in, rgb, blank_n, hs_n, vs_n);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input permit;
  wire permit;
  input valid;
  wire valid;
  input [23:0] rgb_in;
  wire [23:0] rgb_in;
  input blank_in;
  wire blank_in;
  input hs_in;
  wire hs_in;
  input vs_in;
  wire vs_in;
  output [23:0] rgb;
  wire [23:0] rgb;
  output blank_n;
  wire blank_n;
  output hs_n;
  wire hs_n;
  output vs_n;
  wire vs_n;
  wire blank_n_OBUF_O_I;
  wire clear;
  wire [23:0] clear_DFFC_CLEAR_Q;
  wire clear_request;
  wire clk_IBUF_I_O;
  wire hs_in_IBUF_I_O;
  wire hs_n_OBUF_O_I;
  wire [1:0] release_pipe;
  wire release_pipe_DFFP_Q_D;
  wire [1:0] reset_IBUF_I_O;
  wire [1:0] rgb_in_IBUF_I_O;
  wire [23:0] rgb_in_IBUF_I_O_LUT2_I0_F;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_10_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_11_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_12_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_13_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_14_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_15_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_16_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_17_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_18_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_19_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_1_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_20_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_22_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_2_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_3_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_4_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_5_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_6_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_7_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_8_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_9_I0;
  wire [1:0] rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_I0;
  wire [1:0] valid_IBUF_I_O;
  wire [1:0] valid_IBUF_I_O_LUT2_I1_F;
  wire vs_in_IBUF_I_O;
  wire vs_n_OBUF_O_I;
  OBUF blank_n_OBUF_O (
    .I(blank_n_OBUF_O_I),
    .O(blank_n)
  );
  DFFC blank_n_OBUF_O_I_DFFC_Q (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(valid_IBUF_I_O_LUT2_I1_F[1]),
    .Q(blank_n_OBUF_O_I)
  );
  DFFC clear_DFFC_CLEAR (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[2]),
    .Q(clear_DFFC_CLEAR_Q[2])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[0]),
    .Q(clear_DFFC_CLEAR_Q[0])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_1 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[1]),
    .Q(clear_DFFC_CLEAR_Q[1])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_10 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[15]),
    .Q(clear_DFFC_CLEAR_Q[15])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_11 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[14]),
    .Q(clear_DFFC_CLEAR_Q[14])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_12 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[13]),
    .Q(clear_DFFC_CLEAR_Q[13])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_13 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[12]),
    .Q(clear_DFFC_CLEAR_Q[12])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_14 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[11]),
    .Q(clear_DFFC_CLEAR_Q[11])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_15 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[10]),
    .Q(clear_DFFC_CLEAR_Q[10])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_16 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[9]),
    .Q(clear_DFFC_CLEAR_Q[9])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_17 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[8]),
    .Q(clear_DFFC_CLEAR_Q[8])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_18 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[7]),
    .Q(clear_DFFC_CLEAR_Q[7])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_19 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[6]),
    .Q(clear_DFFC_CLEAR_Q[6])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_2 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[23]),
    .Q(clear_DFFC_CLEAR_Q[23])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_20 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[5]),
    .Q(clear_DFFC_CLEAR_Q[5])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_21 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[4]),
    .Q(clear_DFFC_CLEAR_Q[4])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_22 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[3]),
    .Q(clear_DFFC_CLEAR_Q[3])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_3 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[22]),
    .Q(clear_DFFC_CLEAR_Q[22])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_4 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[21]),
    .Q(clear_DFFC_CLEAR_Q[21])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_5 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[20]),
    .Q(clear_DFFC_CLEAR_Q[20])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_6 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[19]),
    .Q(clear_DFFC_CLEAR_Q[19])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_7 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[18]),
    .Q(clear_DFFC_CLEAR_Q[18])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_8 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[17]),
    .Q(clear_DFFC_CLEAR_Q[17])
  );
  DFFC clear_DFFC_CLEAR_Q_DFFC_Q_9 (
    .CLEAR(clear),
    .CLK(clk_IBUF_I_O),
    .D(rgb_in_IBUF_I_O_LUT2_I0_F[16]),
    .Q(clear_DFFC_CLEAR_Q[16])
  );
  DFFP clear_DFFP_Q (
    .CLK(clk_IBUF_I_O),
    .D(release_pipe[0]),
    .PRESET(clear_request),
    .Q(clear)
  );
  LUT2 #(
    .INIT(4'hd)
  ) clear_request_LUT2_F (
    .F(clear_request),
    .I0(reset_IBUF_I_O[0]),
    .I1(reset_IBUF_I_O[1])
  );
  IBUF clk_IBUF_I (
    .I(clk),
    .O(clk_IBUF_I_O)
  );
  IBUF hs_in_IBUF_I (
    .I(hs_in),
    .O(hs_in_IBUF_I_O)
  );
  OBUF hs_n_OBUF_O (
    .I(hs_n_OBUF_O_I),
    .O(hs_n)
  );
  DFFP hs_n_OBUF_O_I_DFFP_Q (
    .CLK(clk_IBUF_I_O),
    .D(hs_in_IBUF_I_O),
    .PRESET(clear),
    .Q(hs_n_OBUF_O_I)
  );
  DFFP release_pipe_DFFP_Q (
    .CLK(clk_IBUF_I_O),
    .D(release_pipe_DFFP_Q_D),
    .PRESET(clear_request),
    .Q(release_pipe[0])
  );
  GND release_pipe_DFFP_Q_D_GND_G (
    .G(release_pipe_DFFP_Q_D)
  );
  IBUF reset_IBUF_I (
    .I(reset),
    .O(reset_IBUF_I_O[1])
  );
  IBUF reset_IBUF_I_O_IBUF_O (
    .I(permit),
    .O(reset_IBUF_I_O[0])
  );
  OBUF rgb_OBUF_O (
    .I(clear_DFFC_CLEAR_Q[9]),
    .O(rgb[9])
  );
  OBUF rgb_OBUF_O_1 (
    .I(clear_DFFC_CLEAR_Q[8]),
    .O(rgb[8])
  );
  OBUF rgb_OBUF_O_10 (
    .I(clear_DFFC_CLEAR_Q[20]),
    .O(rgb[20])
  );
  OBUF rgb_OBUF_O_11 (
    .I(clear_DFFC_CLEAR_Q[2]),
    .O(rgb[2])
  );
  OBUF rgb_OBUF_O_12 (
    .I(clear_DFFC_CLEAR_Q[19]),
    .O(rgb[19])
  );
  OBUF rgb_OBUF_O_13 (
    .I(clear_DFFC_CLEAR_Q[18]),
    .O(rgb[18])
  );
  OBUF rgb_OBUF_O_14 (
    .I(clear_DFFC_CLEAR_Q[17]),
    .O(rgb[17])
  );
  OBUF rgb_OBUF_O_15 (
    .I(clear_DFFC_CLEAR_Q[16]),
    .O(rgb[16])
  );
  OBUF rgb_OBUF_O_16 (
    .I(clear_DFFC_CLEAR_Q[15]),
    .O(rgb[15])
  );
  OBUF rgb_OBUF_O_17 (
    .I(clear_DFFC_CLEAR_Q[14]),
    .O(rgb[14])
  );
  OBUF rgb_OBUF_O_18 (
    .I(clear_DFFC_CLEAR_Q[13]),
    .O(rgb[13])
  );
  OBUF rgb_OBUF_O_19 (
    .I(clear_DFFC_CLEAR_Q[12]),
    .O(rgb[12])
  );
  OBUF rgb_OBUF_O_2 (
    .I(clear_DFFC_CLEAR_Q[7]),
    .O(rgb[7])
  );
  OBUF rgb_OBUF_O_20 (
    .I(clear_DFFC_CLEAR_Q[11]),
    .O(rgb[11])
  );
  OBUF rgb_OBUF_O_21 (
    .I(clear_DFFC_CLEAR_Q[10]),
    .O(rgb[10])
  );
  OBUF rgb_OBUF_O_22 (
    .I(clear_DFFC_CLEAR_Q[1]),
    .O(rgb[1])
  );
  OBUF rgb_OBUF_O_23 (
    .I(clear_DFFC_CLEAR_Q[0]),
    .O(rgb[0])
  );
  OBUF rgb_OBUF_O_3 (
    .I(clear_DFFC_CLEAR_Q[6]),
    .O(rgb[6])
  );
  OBUF rgb_OBUF_O_4 (
    .I(clear_DFFC_CLEAR_Q[5]),
    .O(rgb[5])
  );
  OBUF rgb_OBUF_O_5 (
    .I(clear_DFFC_CLEAR_Q[4]),
    .O(rgb[4])
  );
  OBUF rgb_OBUF_O_6 (
    .I(clear_DFFC_CLEAR_Q[3]),
    .O(rgb[3])
  );
  OBUF rgb_OBUF_O_7 (
    .I(clear_DFFC_CLEAR_Q[23]),
    .O(rgb[23])
  );
  OBUF rgb_OBUF_O_8 (
    .I(clear_DFFC_CLEAR_Q[22]),
    .O(rgb[22])
  );
  OBUF rgb_OBUF_O_9 (
    .I(clear_DFFC_CLEAR_Q[21]),
    .O(rgb[21])
  );
  IBUF rgb_in_IBUF_I (
    .I(rgb_in[9]),
    .O(rgb_in_IBUF_I_O[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[9]),
    .I0(rgb_in_IBUF_I_O[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[22]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_1 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[21]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_1_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_10 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[12]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_10_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_10_I0_IBUF_O (
    .I(rgb_in[12]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_10_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_11 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[11]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_11_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_11_I0_IBUF_O (
    .I(rgb_in[11]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_11_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_12 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[10]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_12_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_12_I0_IBUF_O (
    .I(rgb_in[10]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_12_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_13 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[8]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_13_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_13_I0_IBUF_O (
    .I(rgb_in[8]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_13_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_14 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[7]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_14_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_14_I0_IBUF_O (
    .I(rgb_in[7]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_14_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_15 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[6]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_15_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_15_I0_IBUF_O (
    .I(rgb_in[6]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_15_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_16 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[5]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_16_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_16_I0_IBUF_O (
    .I(rgb_in[5]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_16_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_17 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[4]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_17_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_17_I0_IBUF_O (
    .I(rgb_in[4]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_17_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_18 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[3]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_18_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_18_I0_IBUF_O (
    .I(rgb_in[3]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_18_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_19 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[2]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_19_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_19_I0_IBUF_O (
    .I(rgb_in[2]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_19_I0[0])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_1_I0_IBUF_O (
    .I(rgb_in[21]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_1_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_2 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[20]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_2_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_20 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[1]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_20_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_20_I0_IBUF_O (
    .I(rgb_in[1]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_20_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_21 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[23]),
    .I0(valid_IBUF_I_O_LUT2_I1_F[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_22 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[0]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_22_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_22_I0_IBUF_O (
    .I(rgb_in[0]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_22_I0[0])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_2_I0_IBUF_O (
    .I(rgb_in[20]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_2_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_3 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[19]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_3_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_3_I0_IBUF_O (
    .I(rgb_in[19]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_3_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_4 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[18]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_4_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_4_I0_IBUF_O (
    .I(rgb_in[18]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_4_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_5 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[17]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_5_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_5_I0_IBUF_O (
    .I(rgb_in[17]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_5_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_6 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[16]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_6_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_6_I0_IBUF_O (
    .I(rgb_in[16]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_6_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_7 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[15]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_7_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_7_I0_IBUF_O (
    .I(rgb_in[15]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_7_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_8 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[14]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_8_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_8_I0_IBUF_O (
    .I(rgb_in[14]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_8_I0[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_9 (
    .F(rgb_in_IBUF_I_O_LUT2_I0_F[13]),
    .I0(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_9_I0[0]),
    .I1(valid_IBUF_I_O_LUT2_I1_F[1])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_9_I0_IBUF_O (
    .I(rgb_in[13]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_9_I0[0])
  );
  IBUF rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_I0_IBUF_O (
    .I(rgb_in[22]),
    .O(rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_I0[0])
  );
  IBUF valid_IBUF_I (
    .I(valid),
    .O(valid_IBUF_I_O[1])
  );
  IBUF valid_IBUF_I_O_IBUF_O (
    .I(blank_in),
    .O(valid_IBUF_I_O[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) valid_IBUF_I_O_LUT2_I1 (
    .F(valid_IBUF_I_O_LUT2_I1_F[1]),
    .I0(valid_IBUF_I_O[0]),
    .I1(valid_IBUF_I_O[1])
  );
  IBUF valid_IBUF_I_O_LUT2_I1_F_IBUF_O (
    .I(rgb_in[23]),
    .O(valid_IBUF_I_O_LUT2_I1_F[0])
  );
  IBUF vs_in_IBUF_I (
    .I(vs_in),
    .O(vs_in_IBUF_I_O)
  );
  OBUF vs_n_OBUF_O (
    .I(vs_n_OBUF_O_I),
    .O(vs_n)
  );
  DFFP vs_n_OBUF_O_I_DFFP_Q (
    .CLK(clk_IBUF_I_O),
    .D(vs_in_IBUF_I_O),
    .PRESET(clear),
    .Q(vs_n_OBUF_O_I)
  );
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_12_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_6_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_14_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_5_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_10_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_4_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_15_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_3_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_2_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_16_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_1_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_9_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_17_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_11_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_18_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_8_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_19_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_13_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_20_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_7_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign rgb_in_IBUF_I_O_LUT2_I0_F_LUT2_F_22_I0[1] = valid_IBUF_I_O_LUT2_I1_F[1];
  assign release_pipe[1] = clear;
endmodule
