/* Generated by Yosys 0.69 (git sha1 9f75ca1f9, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

module configuration_reset(clk_ref, reset);
  input clk_ref;
  wire clk_ref;
  output reset;
  wire reset;
  wire [1:0] released;
  wire released_DFF_Q_D;
  DFF released_DFF_Q (
    .CLK(clk_ref),
    .D(released_DFF_Q_D),
    .Q(released[0])
  );
  DFF released_DFF_Q_1 (
    .CLK(clk_ref),
    .D(released[0]),
    .Q(released[1])
  );
  VCC released_DFF_Q_D_VCC_V (
    .V(released_DFF_Q_D)
  );
  LUT1 #(
    .INIT(2'h1)
  ) reset_LUT1_F (
    .F(reset),
    .I0(released[1])
  );
endmodule
