/* Generated by Yosys 0.69 (git sha1 9f75ca1f9, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

module configuration_reset(clk_ref, reset);
  input clk_ref;
  wire clk_ref;
  output reset;
  wire reset;
  wire [64:0] released;
  wire released_DFF_Q_D;
  DFF released_DFF_Q (
    .CLK(clk_ref),
    .D(released_DFF_Q_D),
    .Q(released[0])
  );
  DFF released_DFF_Q_1 (
    .CLK(clk_ref),
    .D(released[63]),
    .Q(released[64])
  );
  DFF released_DFF_Q_10 (
    .CLK(clk_ref),
    .D(released[54]),
    .Q(released[55])
  );
  DFF released_DFF_Q_11 (
    .CLK(clk_ref),
    .D(released[53]),
    .Q(released[54])
  );
  DFF released_DFF_Q_12 (
    .CLK(clk_ref),
    .D(released[52]),
    .Q(released[53])
  );
  DFF released_DFF_Q_13 (
    .CLK(clk_ref),
    .D(released[51]),
    .Q(released[52])
  );
  DFF released_DFF_Q_14 (
    .CLK(clk_ref),
    .D(released[50]),
    .Q(released[51])
  );
  DFF released_DFF_Q_15 (
    .CLK(clk_ref),
    .D(released[49]),
    .Q(released[50])
  );
  DFF released_DFF_Q_16 (
    .CLK(clk_ref),
    .D(released[48]),
    .Q(released[49])
  );
  DFF released_DFF_Q_17 (
    .CLK(clk_ref),
    .D(released[47]),
    .Q(released[48])
  );
  DFF released_DFF_Q_18 (
    .CLK(clk_ref),
    .D(released[46]),
    .Q(released[47])
  );
  DFF released_DFF_Q_19 (
    .CLK(clk_ref),
    .D(released[45]),
    .Q(released[46])
  );
  DFF released_DFF_Q_2 (
    .CLK(clk_ref),
    .D(released[62]),
    .Q(released[63])
  );
  DFF released_DFF_Q_20 (
    .CLK(clk_ref),
    .D(released[44]),
    .Q(released[45])
  );
  DFF released_DFF_Q_21 (
    .CLK(clk_ref),
    .D(released[43]),
    .Q(released[44])
  );
  DFF released_DFF_Q_22 (
    .CLK(clk_ref),
    .D(released[42]),
    .Q(released[43])
  );
  DFF released_DFF_Q_23 (
    .CLK(clk_ref),
    .D(released[41]),
    .Q(released[42])
  );
  DFF released_DFF_Q_24 (
    .CLK(clk_ref),
    .D(released[40]),
    .Q(released[41])
  );
  DFF released_DFF_Q_25 (
    .CLK(clk_ref),
    .D(released[39]),
    .Q(released[40])
  );
  DFF released_DFF_Q_26 (
    .CLK(clk_ref),
    .D(released[38]),
    .Q(released[39])
  );
  DFF released_DFF_Q_27 (
    .CLK(clk_ref),
    .D(released[37]),
    .Q(released[38])
  );
  DFF released_DFF_Q_28 (
    .CLK(clk_ref),
    .D(released[36]),
    .Q(released[37])
  );
  DFF released_DFF_Q_29 (
    .CLK(clk_ref),
    .D(released[35]),
    .Q(released[36])
  );
  DFF released_DFF_Q_3 (
    .CLK(clk_ref),
    .D(released[61]),
    .Q(released[62])
  );
  DFF released_DFF_Q_30 (
    .CLK(clk_ref),
    .D(released[34]),
    .Q(released[35])
  );
  DFF released_DFF_Q_31 (
    .CLK(clk_ref),
    .D(released[33]),
    .Q(released[34])
  );
  DFF released_DFF_Q_32 (
    .CLK(clk_ref),
    .D(released[32]),
    .Q(released[33])
  );
  DFF released_DFF_Q_33 (
    .CLK(clk_ref),
    .D(released[31]),
    .Q(released[32])
  );
  DFF released_DFF_Q_34 (
    .CLK(clk_ref),
    .D(released[30]),
    .Q(released[31])
  );
  DFF released_DFF_Q_35 (
    .CLK(clk_ref),
    .D(released[29]),
    .Q(released[30])
  );
  DFF released_DFF_Q_36 (
    .CLK(clk_ref),
    .D(released[28]),
    .Q(released[29])
  );
  DFF released_DFF_Q_37 (
    .CLK(clk_ref),
    .D(released[27]),
    .Q(released[28])
  );
  DFF released_DFF_Q_38 (
    .CLK(clk_ref),
    .D(released[26]),
    .Q(released[27])
  );
  DFF released_DFF_Q_39 (
    .CLK(clk_ref),
    .D(released[25]),
    .Q(released[26])
  );
  DFF released_DFF_Q_4 (
    .CLK(clk_ref),
    .D(released[60]),
    .Q(released[61])
  );
  DFF released_DFF_Q_40 (
    .CLK(clk_ref),
    .D(released[24]),
    .Q(released[25])
  );
  DFF released_DFF_Q_41 (
    .CLK(clk_ref),
    .D(released[23]),
    .Q(released[24])
  );
  DFF released_DFF_Q_42 (
    .CLK(clk_ref),
    .D(released[22]),
    .Q(released[23])
  );
  DFF released_DFF_Q_43 (
    .CLK(clk_ref),
    .D(released[21]),
    .Q(released[22])
  );
  DFF released_DFF_Q_44 (
    .CLK(clk_ref),
    .D(released[20]),
    .Q(released[21])
  );
  DFF released_DFF_Q_45 (
    .CLK(clk_ref),
    .D(released[19]),
    .Q(released[20])
  );
  DFF released_DFF_Q_46 (
    .CLK(clk_ref),
    .D(released[18]),
    .Q(released[19])
  );
  DFF released_DFF_Q_47 (
    .CLK(clk_ref),
    .D(released[17]),
    .Q(released[18])
  );
  DFF released_DFF_Q_48 (
    .CLK(clk_ref),
    .D(released[16]),
    .Q(released[17])
  );
  DFF released_DFF_Q_49 (
    .CLK(clk_ref),
    .D(released[15]),
    .Q(released[16])
  );
  DFF released_DFF_Q_5 (
    .CLK(clk_ref),
    .D(released[59]),
    .Q(released[60])
  );
  DFF released_DFF_Q_50 (
    .CLK(clk_ref),
    .D(released[14]),
    .Q(released[15])
  );
  DFF released_DFF_Q_51 (
    .CLK(clk_ref),
    .D(released[13]),
    .Q(released[14])
  );
  DFF released_DFF_Q_52 (
    .CLK(clk_ref),
    .D(released[12]),
    .Q(released[13])
  );
  DFF released_DFF_Q_53 (
    .CLK(clk_ref),
    .D(released[11]),
    .Q(released[12])
  );
  DFF released_DFF_Q_54 (
    .CLK(clk_ref),
    .D(released[10]),
    .Q(released[11])
  );
  DFF released_DFF_Q_55 (
    .CLK(clk_ref),
    .D(released[9]),
    .Q(released[10])
  );
  DFF released_DFF_Q_56 (
    .CLK(clk_ref),
    .D(released[8]),
    .Q(released[9])
  );
  DFF released_DFF_Q_57 (
    .CLK(clk_ref),
    .D(released[7]),
    .Q(released[8])
  );
  DFF released_DFF_Q_58 (
    .CLK(clk_ref),
    .D(released[6]),
    .Q(released[7])
  );
  DFF released_DFF_Q_59 (
    .CLK(clk_ref),
    .D(released[5]),
    .Q(released[6])
  );
  DFF released_DFF_Q_6 (
    .CLK(clk_ref),
    .D(released[58]),
    .Q(released[59])
  );
  DFF released_DFF_Q_60 (
    .CLK(clk_ref),
    .D(released[4]),
    .Q(released[5])
  );
  DFF released_DFF_Q_61 (
    .CLK(clk_ref),
    .D(released[3]),
    .Q(released[4])
  );
  DFF released_DFF_Q_62 (
    .CLK(clk_ref),
    .D(released[2]),
    .Q(released[3])
  );
  DFF released_DFF_Q_63 (
    .CLK(clk_ref),
    .D(released[1]),
    .Q(released[2])
  );
  DFF released_DFF_Q_64 (
    .CLK(clk_ref),
    .D(released[0]),
    .Q(released[1])
  );
  DFF released_DFF_Q_7 (
    .CLK(clk_ref),
    .D(released[57]),
    .Q(released[58])
  );
  DFF released_DFF_Q_8 (
    .CLK(clk_ref),
    .D(released[56]),
    .Q(released[57])
  );
  DFF released_DFF_Q_9 (
    .CLK(clk_ref),
    .D(released[55]),
    .Q(released[56])
  );
  VCC released_DFF_Q_D_VCC_V (
    .V(released_DFF_Q_D)
  );
  LUT1 #(
    .INIT(2'h1)
  ) reset_LUT1_F (
    .F(reset),
    .I0(released[64])
  );
endmodule
